<#
  .SYNOPSIS
  自动化三审 Code Review
  1. Codex Reviewer — 逻辑/边界 case
  2. Gemini Code Assist — 已在 GitHub 自动评论（GitHub App）
  3. Claude Code Reviewer — 复核（只标记 critical）
#>
param(
    [Parameter(Mandatory)] [int] $PRNumber,
    [Parameter(Mandatory)] [string] $Repo
)

$ErrorActionPreference = "Stop"

# 获取 PR diff（不 checkout，避免 worktree 冲突）
$diff = gh pr diff $PRNumber --repo $Repo
if (-not $diff) {
    Write-Error "Failed to get diff for PR #$PRNumber"
    exit 1
}

# 保存 diff 到临时文件（避免 here-string 问题）
$diffFile = Join-Path $env:TEMP "pr-$PRNumber-diff.txt"
Set-Content -Path $diffFile -Value $diff

# --- Reviewer 1: Codex (逻辑深度) ---
$codexPromptFile = Join-Path $env:TEMP "pr-$PRNumber-codex-prompt.txt"
@"
你是一位严格的代码审查员。审查以下 PR diff，重点关注：
1. 逻辑错误、边界 case、竞态条件
2. 错误处理是否完善
3. 性能隐患
4. 测试覆盖

请输出结构化的 review 评论，每条必须标注严重程度：
- [CRITICAL] — 必须修复，阻塞合并
- [WARNING] — 建议修复
- [NIT] — 可忽略的小问题

DIFF:
"@ | Set-Content -Path $codexPromptFile
Add-Content -Path $codexPromptFile -Value (Get-Content $diffFile -Raw)

$codexReviewFile = Join-Path $env:TEMP "pr-$PRNumber-codex-review.txt"
try {
    codex exec -m gpt-5.3-codex --dangerously-bypass-approvals-and-sandbox -p (Get-Content $codexPromptFile -Raw) > $codexReviewFile 2>$null
} catch {
    Write-Host "Codex review skipped: $_"
    "Codex review unavailable" | Set-Content $codexReviewFile
}

# --- Reviewer 2: Claude (复核，只提 critical) ---
$claudePromptFile = Join-Path $env:TEMP "pr-$PRNumber-claude-prompt.txt"
$codexReview = Get-Content $codexReviewFile -Raw
@"
你是一位保守的代码审查员。基于以下 review，只输出你认为真正 critical 的问题。
如果没有什么 critical 的，回复 "LGTM" 即可。

Review:
$codexReview
"@ | Set-Content -Path $claudePromptFile

$claudeReviewFile = Join-Path $env:TEMP "pr-$PRNumber-claude-review.txt"
try {
    claude --dangerously-skip-permissions -p (Get-Content $claudePromptFile -Raw) > $claudeReviewFile 2>$null
} catch {
    Write-Host "Claude review skipped: $_"
    "LGTM" | Set-Content $claudeReviewFile
}

# 合并 review 并评论到 PR
$combined = @"
## AI Code Review (Auto-generated)

### Codex Reviewer (Logic & Edge Cases)
$(Get-Content $codexReviewFile -Raw)

### Claude Reviewer (Critical Only)
$(Get-Content $claudeReviewFile -Raw)

---
*Generated by Agent Swarm Review Pipeline*
"@

$commentFile = Join-Path $env:TEMP "pr-$PRNumber-comment.txt"
Set-Content -Path $commentFile -Value $combined
gh pr comment $PRNumber --repo $Repo --body-file $commentFile
Remove-Item $commentFile -ErrorAction SilentlyContinue

Write-Host "Review posted to PR #$PRNumber"
